### ISSUE TITLE
install problem log

### ISSUE THREAD

**Issue by bingo9062** [zixia/node-facenet#66]
> python3 -m venv python3 && . python3/bin/activate && pip3 install -r requirements.txt

Error: Command '['/home/neon/node_modules/facenet/python3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! facenet@0.3.19 venv: `python3 -m venv python3 && . python3/bin/activate && pip3 install -r requirements.txt`

**Comment by henrych4** [comment]
It happened to me as well. And after I reinstalled python3.6, problem seems gone.

**Comment by bingo9062** [comment]
yeah! after reinstall python3.It can be run well,thank you!

**Comment by bobiblazeski** [comment]
I'm having the same problem with installation of node-facenet

> 10942 verbose node v8.11.1
> 10943 verbose npm  v5.6.0
> 10944 error code ELIFECYCLE
> 10945 error errno 1
> 10946 error facenet@0.10.3 postinstall: `npm run venv && npm run postinstall:facenet && npm run postinstall:models`
> 10946 error Exit status 1
> 10947 error Failed at the facenet@0.10.3 postinstall script.
> 10947 error This is probably not a problem with npm. There is likely additional logging output above.
> 10948 verbose exit [ 1, true ]
> slobodan@deus:~/testface$ python --version
> Python 3.6.2 :: Anaconda custom (64-bit)
