### ISSUE TITLE
Is there good way to restore Face object from flashstore?  thanks

### ISSUE THREAD

**Issue by bingo9062** [zixia/node-facenet#78]
My purpose is to store lots of picture for face recognization database.When i store face by using toJSON() and flashstore and restore json from flashstore to Face object I  got problem.
Is there any good implement please?thanks!

    This is my code:

    const imageFile = `/home/neon/Desktop/download/1.jpg`
    const faceList = await facenet.align(imageFile)// Do Face Alignment, return faces
    faceList[0].embedding = await facenet.embedding(faceList[0])
    const flashStore = new FlashStore('falshstore.workdir')
    await flashStore.put(1, faceList[0].toJSON())    //store face type FaceJsonObject
    flashStore.get(1)//get face from database 
    Face.fromJSON(flashStore.get(1))

**Comment by zixia** [comment]
Your code looks should work.

What's your expected output and what's the actual output?

**Comment by bingo9062** [comment]
1)My expected output is Face object from flashStore.get(1)

2)When it execute to "Face.fromJSON(flashStore.get(1))" i got:

'Error'message: 'Argument of type 'Promise<{} | null>' is not assignable to parameter of type 'string | FaceJsonObject'.
  Type 'Promise<{} | null>' is not assignable to type 'FaceJsonObject'.
    Property 'embedding' is missing in type 'Promise<{} | null>'.'
3)how to convert the flashStore.get(1) result to an Face object?

**Comment by zixia** [comment]
You need to use `await` to resolve the promise.

like:

```ts
Face.fromJSON(await flashStore.get(1))
```

**Comment by zixia** [comment]
However, I'd like to suggest you to use the `FaceCache` class to manage the Face for you instead of by yourself.

See: https://github.com/zixia/face-blinder/blob/365dd1f9e820f125274ea25a150b9dbd0fec3dd4/src/face-blinder.ts#L208-L232

**Comment by bingo9062** [comment]
Thanks zixia！ I have use your face-blinder implement my purpose.
The time which i recognize one jpg is 30 seconds.
My gpu is a nvdia 1080ti. Is that run normal? May it run faster?
 Thanks！

**Comment by zixia** [comment]
Great to hear that!

I believe you are still running facenet on your CPU because it should be faster if you are using a GPU.

I guess it should run no more than 1 seconds, more likely should less than 100ms on your 1080 GPU.

**Comment by bingo9062** [comment]
lol thanks :
I run the script by excute "ts-node recognize.ts"in cmmand line.
How to execute the face-blinder on my gpu?

**Comment by zixia** [comment]
Just read the code... 

I had never do that before, so please let me know if get it to work... ;-)

**Comment by bingo9062** [comment]
Sorry!  I  have misunderstood the time costed.
Init progress have take almost 30 seconds and recognize progress just cost 20 milliseconds.
But i think the facenet is still running on my cpu,it may take a bit of effort to rewirte facenet for Gpu.
                                                                                                                       Sincerely thanks!

**Comment by zixia** [comment]
Congratulations.

I believe you need not have to rewrite facenet, but only try to find the right place to set the parameter right for your GPU setting.
