### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by staminna** [zixia/node-facenet#99]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
Portugal
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
Localhost
### Expected behavior

git clone

### Actual behavior

permission denied

### Steps to reproduce the behavior (and fixes, if any)

s$ git clone git@github.com:zixia/node-facenet.git
Cloning into 'node-facenet'...
\The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes     
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zixia** [comment]
You did not set your public key right.

The solution for you is to use https instead of git:
```
git clone https://github.com/zixia/node-facenet.git
```
